name: Update skins

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "40 * * * *"

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  skins:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10.4
        uses: actions/setup-python@v3.1.2
        with:
          python-version: 3.10.4

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Update skins
        run: python skins.py

      - name: 🚀 Deploy changes
        run: |
          # set git author
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "Auto-update"
          # finally push
          git push
